# fly.toml app configuration file generated for barkley on 2024-03-16T23:25:24+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'barkley'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  RACK_ENV = "production"
  PORT=8080

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
