#! /usr/bin/env ruby

require "json"
require "net/http"

force = ENV["FORCE"]

# https://generator.jspm.io/#U2VhYGBkDM0rySzJSU1hcEjPLMkoTdIvSs1JLMksS9UtycxN1U3NSc1NzStxMNEz1jMEAP7dw1YyAA
#
# Get things from jspm.io, paste it below the __END__, then run this and past the output somewhere in a view
#
# But then maybe you also need to still fetch the dependencies you'll see when you hit the preload toggle:
#
#      curl -O "https://ga.jspm.io/npm:@github/relative-time-element@4.3.1/dist/relative-time-element-define.js"
#      curl -O "https://ga.jspm.io/npm:@github/relative-time-element@4.3.1/dist/relative-time-element.js"
#
# Sigh. Like most meetings could have been emails, most javascript could have been less javascript

import_map = JSON.parse(DATA.read)
root = File.expand_path(File.join(File.dirname(__FILE__), ".."))

map = {
  env: [
    "browser",
    "production",
    "module"
  ],
  imports: {}
}

to_import = import_map["imports"]
import_map.fetch("scopes", []).each do |_key, values|
  to_import.merge!(values)
end

def path_for(root, name)= File.join(root, "public/dist/#{name}")
def safe_name(name)= name.gsub("/", "--") + ".js"

def download(name, url, force: false)
  root = File.expand_path(File.join(File.dirname(__FILE__), ".."))
  path = File.join(root, "public/dist/#{name}")
  return if File.exist?(path) && !force

  puts "Downloading #{name} at #{url}"

  uri = URI.parse(url)
  response = Net::HTTP.get_response(uri)
  File.open(path, "w") do |f|
    f.write response.body
  end
end

to_import.each do |name, url|
  download(safe_name(name), url, force: force)
  download(safe_name(name)+ ".map", url + ".map", force: force)
  map[:imports][name] = "<%= timestamp_path(xxx./dist/#{safe_name(name)}xxx) %>"
end

module_shims_version = "2.0.10"
download("es-module-shims.js", "https://ga.jspm.io/npm:es-module-shims@#{module_shims_version}/dist/es-module-shims.js", force: force)
download("es-module-shims.js.map", "https://ga.jspm.io/npm:es-module-shims@#{module_shims_version}/dist/es-module-shims.js.map", force: force)

relative_time_version = "4.4.5"
download("relative-time-element-define.js", "https://ga.jspm.io/npm:@github/relative-time-element@#{relative_time_version}/dist/relative-time-element-define.js", force: force)
download("relative-time-element.js", "https://ga.jspm.io/npm:@github/relative-time-element@#{relative_time_version}/dist/relative-time-element.js", force: force)

puts JSON.pretty_generate(map)

__END__
{
  "imports": {
    "@github/relative-time-element": "https://ga.jspm.io/npm:@github/relative-time-element@4.4.5/dist/index.js"
  }
}
