data = {
  :albert => {
   loop_1_start: nil,
   loop_1_finish: nil,
   loop_2_start: nil,
   loop_2_finish: nil,
   loop_3_start: nil,
   loop_3_finish: nil,
   loop_4_start: nil,
   loop_4_finish: nil,
   loop_5_start: nil,
   loop_5_finish: nil,
 },
 :christophe => {
   loop_1_start: nil,
   loop_1_finish: nil,
   loop_2_start: nil,
   loop_2_finish: nil,
   loop_3_start: nil,
   loop_3_finish: nil,
   loop_4_start: nil,
   loop_4_finish: nil,
   loop_5_start: nil,
   loop_5_finish: nil,
 },
 :damian => {
   loop_1_start: nil,
   loop_1_finish: nil,
   loop_2_start: nil,
   loop_2_finish: nil,
   loop_3_start: nil,
   loop_3_finish: nil,
   loop_4_start: nil,
   loop_4_finish: nil,
   loop_5_start: nil,
   loop_5_finish: nil,
 },
 :filippo => {
   loop_1_start: nil,
   loop_1_finish: nil,
   loop_2_start: nil,
   loop_2_finish: nil,
   loop_3_start: nil,
   loop_3_finish: nil,
   loop_4_start: nil,
   loop_4_finish: nil,
   loop_5_start: nil,
   loop_5_finish: nil,
 },
 :harvey => {
   loop_1_start: nil,
   loop_1_finish: nil,
   loop_2_start: nil,
   loop_2_finish: nil,
   loop_3_start: nil,
   loop_3_finish: nil,
   loop_4_start: nil,
   loop_4_finish: nil,
   loop_5_start: nil,
   loop_5_finish: nil,
 },
 :jasmin => {
   loop_1_start: nil,
   loop_1_finish: nil,
   loop_2_start: nil,
   loop_2_finish: nil,
   loop_3_start: nil,
   loop_3_finish: nil,
   loop_4_start: nil,
   loop_4_finish: nil,
   loop_5_start: nil,
   loop_5_finish: nil,
 },
 :john => {
   loop_1_start: nil,
   loop_1_finish: nil,
   loop_2_start: nil,
   loop_2_finish: nil,
   loop_3_start: nil,
   loop_3_finish: nil,
   loop_4_start: nil,
   loop_4_finish: nil,
   loop_5_start: nil,
   loop_5_finish: nil,
 },
 :christiana => {
   loop_1_start: nil,
   loop_1_finish: nil,
   loop_2_start: nil,
   loop_2_finish: nil,
   loop_3_start: nil,
   loop_3_finish: nil,
   loop_4_start: nil,
   loop_4_finish: nil,
   loop_5_start: nil,
   loop_5_finish: nil,
 },
 :maxime => {
   loop_1_start: nil,
   loop_1_finish: nil,
   loop_2_start: nil,
   loop_2_finish: nil,
   loop_3_start: nil,
   loop_3_finish: nil,
   loop_4_start: nil,
   loop_4_finish: nil,
   loop_5_start: nil,
   loop_5_finish: nil,
 },
 :thomas => {
   loop_1_start: nil,
   loop_1_finish: nil,
   loop_2_start: nil,
   loop_2_finish: nil,
   loop_3_start: nil,
   loop_3_finish: nil,
   loop_4_start: nil,
   loop_4_finish: nil,
   loop_5_start: nil,
   loop_5_finish: nil,
 },
 :tomokazu => {
   loop_1_start: nil,
   loop_1_finish: nil,
   loop_2_start: nil,
   loop_2_finish: nil,
   loop_3_start: nil,
   loop_3_finish: nil,
   loop_4_start: nil,
   loop_4_finish: nil,
   loop_5_start: nil,
   loop_5_finish: nil,
 }
}

Barkley.runners.each do |runner|
  runner.loops = data.fetch(runner.slugs.first)
end
